[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/1606325.cloudwaysapps.com/acvqufeuwu/public_html/artisan queue:work redis --tries=1 --timeout=120 --sleep=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=master_cnpgavzpwb
numprocs=1
redirect_stderr=true
stdout_logfile=/home/1606325.cloudwaysapps.com/acvqufeuwu/public_html/storage/logs/worker.log
stopwaitsecs=120
