export const DEPARTMENT_DETAILS_OPTIONS = {
    Site: [
        'Site Meal',
        'Upkeep Motor Vehicle',
        'Upkeep Hostel',
        'Upkeep Office',
        'Maintenance Motor Vehicle',
        'Stationary & Printing',
        'Hardware',
        'Fuel',
        'Travel Expenses',
        'Logistic to Site',
        'Uniform',
        'Tools & Equipment',
        'Welfare',
        'TNG',
        'Advertising',
        'Others',
    ],
    'Human Resource': [
        'Telephone & Wifi',
        'Petrol/Toll/Parking',
        'Postage',
        'Staff Refreshment',
        'Printing & Stationery',
        'Upkeep Office',
        'Staff Uniform',
        'Subscription Fees',
        'Office Equipment',
        'Furniture & Fittings',
        'Recruitment Expenses',
        'Staff Welfare/Medical',
        'Advertising & Promotional Expenses',
        'Computer, Equipment & Software',
        'Staff Accommodation',
        'Others',
    ],
    'Sales Manager': [
        'Staff Refreshment',
        'Marketing',
        'Upkeep Office',
        'Upkeep Showroom',
        'Printing & Stationery',
        'Postage & Stamp',
        'Vehicle & Maintenance',
        'Petrol/Toll/Parking',
        'Staff Accommodation',
        'Advertising & Promotional Expenses',
        'Others',
    ],
};

export const getDetailsOptions = (department) =>
    DEPARTMENT_DETAILS_OPTIONS[department] || DEPARTMENT_DETAILS_OPTIONS.Site;
